import React, { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiClient } from "@/NAYSA Cloud/Configuration/BaseURL.jsx";
import { useAuth } from "@/NAYSA Cloud/Authentication/AuthContext.jsx";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus, faSave, faUndo, faTrashAlt, faEdit } from "@fortawesome/free-solid-svg-icons";
import ButtonBar from "@/NAYSA Cloud/Global/ButtonBar.jsx";
import FieldRenderer from "@/NAYSA Cloud/Global/FieldRenderer.jsx";
import SearchGlobalReferenceTable from "@/NAYSA Cloud/Lookup/SearchGlobalReferenceTable";
import RegistrationInfo from "@/NAYSA Cloud/Global/RegistrationInfo.jsx";
import { LoadingSpinner } from "@/NAYSA Cloud/Global/utilities.jsx";
import { useSwalErrorAlert, useSwalSuccessAlert, useSwalErrorAlertAPI } from "@/NAYSA Cloud/Global/behavior.jsx";

const TABS = ["Personal", "Employment", "Payroll", "Government & Bank", "Schedule", "Access & Approval", "History & Family"];
const YN = [{ value: "Y", label: "Yes" }, { value: "N", label: "No" }];
const DAYS = ["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"].map(x=>({value:x,label:x[0]+x.slice(1).toLowerCase()}));
const blankEmployee = {
  empNo:"", empName:"", lastName:"", firstName:"", middleName:"", address1:"", address2:"", civilStatus:"", gender:"", rdoCode:"", zipCode:"", emailAddress:"", contactNo:"", telNo:"", birthplace:"", contactAddress:"", contactPerson:"", contactRelation:"", contactPhoneno:"",
  yrsService:0, compCode:"", branchCode:"", clientCode:"", payGroup:"", deptCode:"", posCode:"", statCode:"", sgCode:"", level:"", areaCode:"", sssNo:"", tin:"", hdmfNo:"", phNo:"", umid:"", bankCode:"", bankAcct:"", bank2:"", bankCode2:"", bankAcct2:"", bank2Comp:"", bank3:"", bankCode3:"", bankAcct3:"", bank3Comp:"",
  birthdate:"", dateHired:"", dateRegularized:"", dateResigned:"", dateTerminated:"", endContract:"", payrollFreq:"", freqType:"", payMode:"", compSss:"Y", sssFreq:"", compMed:"Y", medFreq:"", compTax:"Y", taxFreq:"", compHdmf:"Y", hdmfFreq:"", taxTable:"", basic:0, dailyRate:0, hourRate:0, regHrs:8, regdaysYear:0, regdaysMonth:0, rendHrs:0, cutoffHrs:0, hdmfEmp:0, hdmfEmpr:0, hdmfMax:0, mpfEmp:0, taxRate:0, ecolaRate:0, cashAllowance:0, allowHrate:0, allowDrate:0, projAllowance:0, tSalary:0, tHrate:0, tDrate:0,
  shiftCode:"", rd1:"", rd2:"", rd3:"", oldEmpno:"", empCode:"", rehired:"N", askappPin:"", askappPw:"", approver:"", app1:"", app2:"", app3:"", supervisor:"", manager:"", geofence:"N", hrFlag:"N", managerFlag:"N", supervisorFlag:"N", activePort:"N", browser:"", loginTime:"", active:"Y"
};
const emptyDetails = { education:[], experience:[], family:[], dependents:[] };

const F = ({label, value, onChange, type="text", options, disabled=false, required=false}) =>
  <FieldRenderer label={label} value={value ?? ""} onChange={onChange} type={type} options={options} disabled={disabled} required={required}/>;

const DetailGrid = ({title, rows, setRows, fields}) => {
  const add = () => setRows([...rows, Object.fromEntries(fields.map(f=>[f.key, ""]))]);
  const change = (i,k,v) => setRows(rows.map((r,x)=>x===i?{...r,[k]:v}:r));
  const remove = i => setRows(rows.filter((_,x)=>x!==i));
  return <div className="border rounded-lg p-3 bg-white dark:bg-gray-800">
    <div className="flex justify-between mb-2"><b className="text-sm">{title}</b><button type="button" onClick={add} className="px-3 py-1 bg-blue-600 text-white rounded text-xs">+ Add</button></div>
    <div className="overflow-auto"><table className="min-w-full text-xs"><thead><tr>{fields.map(f=><th key={f.key} className="p-2 text-left border-b">{f.label}</th>)}<th/></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{fields.map(f=><td key={f.key} className="p-1"><input type={f.type||"text"} value={r[f.key]??""} onChange={e=>change(i,f.key,e.target.value)} className="w-full border rounded px-2 py-1 bg-transparent"/></td>)}<td><button onClick={()=>remove(i)} className="text-red-600"><FontAwesomeIcon icon={faTrashAlt}/></button></td></tr>)}</tbody></table></div>
  </div>;
};

export default function RefEmployee(){
  const {user}=useAuth(); const qc=useQueryClient();
  const [tab,setTab]=useState(TABS[0]); const [employee,setEmployee]=useState(blankEmployee); const [details,setDetails]=useState(emptyDetails); const [selected,setSelected]=useState(null);
  const set=(k,v)=>setEmployee(p=>({...p,[k]:v}));
  const setDetail=(k,v)=>setDetails(p=>({...p,[k]:v}));
  const reset=()=>{setEmployee(blankEmployee);setDetails(emptyDetails);setSelected(null);setTab(TABS[0]);};

  const {data:list=[],isLoading}=useQuery({queryKey:["employeeList"],queryFn:async()=>{const {data}=await apiClient.get('/employee'); const raw=data?.data?.[0]?.result; return raw?JSON.parse(raw):[];}});
  const areas=useQuery({queryKey:["employeeAreas"],queryFn:async()=>{const {data}=await apiClient.get('/area');const raw=data?.data?.[0]?.result;return raw?JSON.parse(raw):[];}}).data||[];
  const areaOptions=areas.filter(x=>String(x.active).toUpperCase()==='Y').map(x=>({value:x.areaCode,label:`${x.areaCode} - ${x.areaName}`}));

  const save=useMutation({mutationFn:p=>apiClient.post('/upsertEmployee',p),onSuccess:r=>{const x=r.data;if(x.errorcount>0||x.success===false)return useSwalErrorAlert('Unable to save',x.errormsg||x.message);qc.invalidateQueries({queryKey:['employeeList']});useSwalSuccessAlert('Success!','Employee saved successfully.');reset();},onError:e=>useSwalErrorAlertAPI('System Error',e)});
  const handleSave=()=>{const empName=employee.empName||`${employee.lastName}, ${employee.firstName}${employee.middleName?` ${employee.middleName}`:''}`.trim(); save.mutate({json_data:JSON.stringify({json_data:{employee:{...employee,empName},...details,userCode:user?.USER_CODE||'ADMIN'}})});};
  const edit=async row=>{try{const {data}=await apiClient.get('/getEmployee',{params:{EMP_NO:row.empNo}});const raw=data?.data?.[0]?.result;if(!raw)return;const x=JSON.parse(raw);const e=typeof x.employee==='string'?JSON.parse(x.employee):x.employee;setEmployee({...blankEmployee,...e});setDetails({education:x.education||[],experience:x.experience||[],family:x.family||[],dependents:x.dependents||[]});setSelected(row.empNo);setTab(TABS[0]);}catch(e){useSwalErrorAlertAPI('Load Employee Error',e)}};

  const columns=useMemo(()=>[
    {key:'__a',label:'Actions',width:80,render:r=><button onClick={()=>edit(r)} className="text-blue-600 px-2"><FontAwesomeIcon icon={faEdit}/></button>},
    {key:'empNo',label:'Employee No.',sortable:true,width:120,requiredVisible:true},{key:'empName',label:'Employee Name',sortable:true,width:260,requiredVisible:true},{key:'branchCode',label:'Branch',width:100},{key:'deptCode',label:'Department',width:120},{key:'posCode',label:'Position',width:120},{key:'statCode',label:'Status',width:100},{key:'active',label:'Active',width:70}
  ],[]);

  const personal=<div className="grid md:grid-cols-2 gap-4"><div className="space-y-3"><F label="Employee No." required value={employee.empNo} disabled={!!selected} onChange={v=>set('empNo',(v||'').toUpperCase())}/><F label="Last Name" required value={employee.lastName} onChange={v=>set('lastName',v)}/><F label="First Name" required value={employee.firstName} onChange={v=>set('firstName',v)}/><F label="Middle Name" value={employee.middleName} onChange={v=>set('middleName',v)}/><F label="Birthdate" type="date" value={employee.birthdate?.slice?.(0,10)||employee.birthdate} onChange={v=>set('birthdate',v)}/><F label="Birthplace" value={employee.birthplace} onChange={v=>set('birthplace',v)}/><F label="Gender" type="select" options={[{value:'MALE',label:'Male'},{value:'FEMALE',label:'Female'}]} value={employee.gender} onChange={v=>set('gender',v)}/><F label="Civil Status" type="select" options={['S','M','W','SEP'].map(x=>({value:x,label:x}))} value={employee.civilStatus} onChange={v=>set('civilStatus',v)}/></div><div className="space-y-3"><F label="Address 1" value={employee.address1} onChange={v=>set('address1',v)}/><F label="Address 2" value={employee.address2} onChange={v=>set('address2',v)}/><F label="ZIP Code" value={employee.zipCode} onChange={v=>set('zipCode',v)}/><F label="Email Address" value={employee.emailAddress} onChange={v=>set('emailAddress',v)}/><F label="Mobile No." value={employee.contactNo} onChange={v=>set('contactNo',v)}/><F label="Emergency Contact" value={employee.contactPerson} onChange={v=>set('contactPerson',v)}/><F label="Relationship" value={employee.contactRelation} onChange={v=>set('contactRelation',v)}/><F label="Emergency Contact No." value={employee.contactPhoneno} onChange={v=>set('contactPhoneno',v)}/></div></div>;
  const employment=<div className="grid md:grid-cols-2 gap-4"><div className="space-y-3">{[['Company','compCode'],['Branch','branchCode'],['Client','clientCode'],['Pay Group','payGroup'],['Department','deptCode'],['Position','posCode'],['Employment Status','statCode'],['Salary Grade','sgCode'],['Level','level']].map(([l,k])=><F key={k} label={l} value={employee[k]} onChange={v=>set(k,v)}/>)}</div><div className="space-y-3"><F label="Area" type="select" options={areaOptions} value={employee.areaCode} onChange={v=>set('areaCode',v)}/>{[['Date Hired','dateHired'],['Date Regularized','dateRegularized'],['End Contract','endContract'],['Date Resigned','dateResigned'],['Date Terminated','dateTerminated']].map(([l,k])=><F key={k} label={l} type="date" value={employee[k]?.slice?.(0,10)||employee[k]} onChange={v=>set(k,v)}/>)}<F label="Old Employee No." value={employee.oldEmpno} onChange={v=>set('oldEmpno',v)}/><F label="Rehired" type="select" options={YN} value={employee.rehired} onChange={v=>set('rehired',v)}/><F label="Active" type="select" options={YN} value={employee.active} onChange={v=>set('active',v)}/></div></div>;
  const payroll=<div className="grid md:grid-cols-3 gap-4">{[['Payroll Frequency','payrollFreq'],['Frequency Type','freqType'],['Pay Mode','payMode'],['Tax Table','taxTable'],['Basic Salary','basic'],['Daily Rate','dailyRate'],['Hourly Rate','hourRate'],['Regular Hours','regHrs'],['Regular Days / Year','regdaysYear'],['Regular Days / Month','regdaysMonth'],['Rendered Hours','rendHrs'],['Cutoff Hours','cutoffHrs'],['ECOLA Rate','ecolaRate'],['Cash Allowance','cashAllowance'],['Allowance Hourly Rate','allowHrate'],['Allowance Daily Rate','allowDrate'],['Project Allowance','projAllowance']].map(([l,k])=><F key={k} label={l} value={employee[k]} onChange={v=>set(k,v)}/>)}</div>;
  const govt=<div className="grid md:grid-cols-2 gap-4"><div className="space-y-3">{[['TIN','tin'],['RDO Code','rdoCode'],['SSS No.','sssNo'],['PhilHealth No.','phNo'],['HDMF No.','hdmfNo'],['UMID','umid'],['Primary Bank','bankCode'],['Primary Account No.','bankAcct']].map(([l,k])=><F key={k} label={l} value={employee[k]} onChange={v=>set(k,v)}/>)}</div><div className="space-y-3">{[['Compute SSS','compSss'],['Compute PhilHealth','compMed'],['Compute Tax','compTax'],['Compute HDMF','compHdmf']].map(([l,k])=><F key={k} label={l} type="select" options={YN} value={employee[k]} onChange={v=>set(k,v)}/>)}{[['HDMF Employee','hdmfEmp'],['HDMF Employer','hdmfEmpr'],['HDMF Maximum','hdmfMax'],['MPF Employee','mpfEmp'],['Tax Rate','taxRate']].map(([l,k])=><F key={k} label={l} value={employee[k]} onChange={v=>set(k,v)}/>)}</div></div>;
  const schedule=<div className="grid md:grid-cols-2 gap-4"><div className="space-y-3"><F label="Default Shift" value={employee.shiftCode} onChange={v=>set('shiftCode',v)}/><F label="Rest Day 1" type="select" options={DAYS} value={employee.rd1} onChange={v=>set('rd1',v)}/><F label="Rest Day 2" type="select" options={DAYS} value={employee.rd2} onChange={v=>set('rd2',v)}/><F label="Rest Day 3" type="select" options={DAYS} value={employee.rd3} onChange={v=>set('rd3',v)}/></div><div><F label="Geofence Required" type="select" options={YN} value={employee.geofence} onChange={v=>set('geofence',v)}/></div></div>;
  const access=<div className="grid md:grid-cols-2 gap-4"><div className="space-y-3">{[['Portal Active','activePort'],['HR','hrFlag'],['Supervisor Flag','supervisorFlag'],['Manager Flag','managerFlag']].map(([l,k])=><F key={k} label={l} type="select" options={YN} value={employee[k]} onChange={v=>set(k,v)}/>)}<F label="Employee Portal Code" value={employee.empCode} onChange={v=>set('empCode',v)}/><F label="PIN" value={employee.askappPin} onChange={v=>set('askappPin',v)}/></div><div className="space-y-3">{[['Approver','approver'],['Approver 1','app1'],['Approver 2','app2'],['Approver 3','app3'],['Supervisor','supervisor'],['Manager','manager']].map(([l,k])=><F key={k} label={l} value={employee[k]} onChange={v=>set(k,v)}/>)}</div></div>;
  const history=<div className="space-y-4"><DetailGrid title="Education" rows={details.education} setRows={v=>setDetail('education',v)} fields={[{key:'level',label:'Level'},{key:'school',label:'School'},{key:'from',label:'From'},{key:'to',label:'To'},{key:'degree',label:'Degree'},{key:'remarks',label:'Remarks'}]}/><DetailGrid title="Employment Experience" rows={details.experience} setRows={v=>setDetail('experience',v)} fields={[{key:'company',label:'Company'},{key:'position',label:'Position'},{key:'from',label:'From'},{key:'to',label:'To'},{key:'leaveReason',label:'Leave Reason'},{key:'remarks',label:'Remarks'}]}/><DetailGrid title="Family" rows={details.family} setRows={v=>setDetail('family',v)} fields={[{key:'familyName',label:'Name'},{key:'familyRelation',label:'Relationship'},{key:'familyBirthdate',label:'Birthdate',type:'date'},{key:'familyAge',label:'Age'},{key:'familyAddress',label:'Address'},{key:'familyContact',label:'Contact'},{key:'familyOccupation',label:'Occupation'}]}/><DetailGrid title="Dependents" rows={details.dependents} setRows={v=>setDetail('dependents',v)} fields={[{key:'dependentName',label:'Name'},{key:'dependentRelation',label:'Relationship'},{key:'dependentBirthdate',label:'Birthdate',type:'date'},{key:'dependentAge',label:'Age'},{key:'dependentAddress',label:'Address'},{key:'dependentContact',label:'Contact'},{key:'dependentOccupation',label:'Occupation'}]}/></div>;
  const content={Personal:personal,Employment:employment,Payroll:payroll,"Government & Bank":govt,Schedule:schedule,"Access & Approval":access,"History & Family":history}[tab];

  return <div className="global-ref-main-div-ui">{(isLoading||save.isPending)&&<LoadingSpinner/>}<div className="global-ref-header-ui mb-2"><div className="flex justify-between items-center"><h1 className="global-ref-headertext-ui">Employee Masterdata</h1><ButtonBar buttons={[{key:'add',label:'Add',icon:faPlus,onClick:reset},{key:'save',label:'Save',icon:faSave,onClick:handleSave},{key:'reset',label:'Reset',icon:faUndo,onClick:reset}]}/></div></div>
    <div className="mt-24 bg-white dark:bg-gray-800 rounded-xl border shadow p-4"><div className="grid md:grid-cols-3 gap-3 mb-4"><F label="Employee No." value={employee.empNo} disabled/><F label="Employee Name" value={employee.empName||`${employee.lastName}, ${employee.firstName}`} disabled/><F label="Status" value={employee.active==='Y'?'Active':'Inactive'} disabled/></div><div className="flex gap-1 overflow-auto border-b mb-4">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 text-xs whitespace-nowrap ${tab===t?'border-b-2 border-blue-600 text-blue-600 font-semibold':'text-gray-500'}`}>{t}</button>)}</div>{content}<div className="mt-4"><RegistrationInfo layout="straight" data={{registeredBy:employee.registeredBy,registeredDate:employee.registeredDate,lastUpdatedBy:employee.updatedBy,lastUpdatedDate:employee.updatedDate}}/></div></div>
    <div className="global-tran-table-main-div-ui mt-4"><SearchGlobalReferenceTable docType="Employee" columns={columns} data={list} isLoading={isLoading} onRowDoubleClick={edit} itemsPerPage={50} autoFillGrid="True"/></div>
  </div>;
}
