import React, { forwardRef, useCallback, useImperativeHandle, useMemo, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft, faCheckSquare, faSquare, faUsers } from "@fortawesome/free-solid-svg-icons";
import { apiClient } from "@/NAYSA Cloud/Configuration/BaseURL.jsx";
import { useSwalErrorAlert, useSwalSuccessAlert } from "@/NAYSA Cloud/Global/behavior.jsx";
import SearchGlobalReferenceTable from "@/NAYSA Cloud/Lookup/SearchGlobalReferenceTable.jsx";
const gu=(r={})=>r.userCode??r.USER_CODE??r.user_code??"";
const gn=(r={})=>r.userName??r.USER_NAME??r.user_name??"";

const groups=[{paygroupCode:"MANCOM",paygroupName:"Mancom"},{paygroupCode:"RANK",paygroupName:"Rank and File"}];
const PaygroupAccessTab=forwardRef(({users=[],tableSize="Half",setSaving},ref)=>{
 const [selectedUsers,setSelectedUsers]=useState([]),[selectedGroups,setSelectedGroups]=useState([]),[viewing,setViewing]=useState(false),[mobileStep,setMobileStep]=useState("users");
 const allUsers=useMemo(()=>users.map(gu).filter(Boolean),[users]);
 const toggleUser=useCallback(c=>{if(!viewing)setSelectedUsers(p=>p.includes(c)?p.filter(x=>x!==c):[...p,c])},[viewing]);
 const toggleGroup=useCallback(c=>setSelectedGroups(p=>p.includes(c)?p.filter(x=>x!==c):[...p,c]),[]);
 const view=()=>{if(!selectedUsers.length)return useSwalErrorAlert("No Users Selected","Please select at least one user.");setViewing(true);setMobileStep("access")};
 const save=useCallback(async()=>{if(!selectedUsers.length)return useSwalErrorAlert("No Users Selected","Please select at least one user.");setSaving?.(true);try{await apiClient.post("/upsertUserPaygroupAccess",{json_data:{dt1:selectedGroups.map(paygroupCode=>({paygroupCode})),dt2:selectedUsers.map(userCode=>({userCode}))}});await useSwalSuccessAlert("Success!","User paygroup access updated successfully!");}catch(e){await useSwalErrorAlert("Error!",e?.response?.data?.message||"Error saving paygroup access.");}finally{setSaving?.(false)}},[selectedUsers,selectedGroups,setSaving]);
 const reset=()=>{setSelectedUsers([]);setSelectedGroups([]);setViewing(false);setMobileStep("users")};
 useImperativeHandle(ref,()=>({save,reset,viewPaygroups:view}));
 const ucols=useMemo(()=>[{key:"__select",label:"Select",width:90,render:r=><div className="flex justify-end md:justify-center py-1"><input type="checkbox" checked={selectedUsers.includes(gu(r))} onChange={()=>toggleUser(gu(r))} onClick={e=>e.stopPropagation()} disabled={viewing} className="h-6 w-6 md:h-4 md:w-4"/></div>},{key:"userCode",label:"User Code",width:150,render:gu},{key:"userName",label:"Username",width:260,render:gn}],[selectedUsers,toggleUser,viewing]);
 return <div className="w-full md:pt-10"><div className="flex flex-col md:flex-row gap-4">
  <div className={`w-full md:w-1/2 ${mobileStep==="users"?"block":"hidden md:block"}`}><div className="bg-white rounded-xl border border-gray-100 shadow-sm p-4 h-full"><div className="flex items-center justify-between mb-2"><h2 className="text-lg font-semibold text-gray-700">Users</h2><button onClick={()=>setSelectedUsers(selectedUsers.length===allUsers.length?[]:[...allUsers])} disabled={viewing} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border border-blue-200 bg-blue-50 text-blue-700 text-xs font-medium"><FontAwesomeIcon icon={selectedUsers.length===allUsers.length?faSquare:faCheckSquare}/>Select All</button></div><SearchGlobalReferenceTable docType="UserAccRight" columns={ucols} data={users} itemsPerPage={50} showFilters onRowClick={r=>toggleUser(gu(r))} onRowDoubleClick={r=>toggleUser(gu(r))} tableSize={tableSize}/></div></div>
  <div className={`w-full md:w-1/2 ${mobileStep==="access"?"block":"hidden md:block"}`}><div className="bg-white rounded-xl border border-gray-100 shadow-sm p-4 h-full"><div className="flex items-center justify-between mb-2"><h2 className="text-lg font-semibold text-gray-700">Paygroups</h2>{viewing&&<button onClick={()=>setSelectedGroups(selectedGroups.length===2?[]:groups.map(g=>g.paygroupCode))} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border border-blue-200 bg-blue-50 text-blue-700 text-xs font-medium"><FontAwesomeIcon icon={selectedGroups.length===2?faSquare:faCheckSquare}/>{selectedGroups.length===2?"Unselect All":"Select All"}</button>}</div>
   {viewing?<div className="space-y-3">{groups.map(g=><button key={g.paygroupCode} onClick={()=>toggleGroup(g.paygroupCode)} className={`w-full rounded-lg border p-4 text-left ${selectedGroups.includes(g.paygroupCode)?"border-blue-300 bg-blue-50":"border-gray-200 bg-white"}`}><div className="flex items-center justify-between"><div><div className="text-sm font-semibold text-gray-800">{g.paygroupName}</div><div className="text-xs text-gray-500">{g.paygroupCode}</div></div><input type="checkbox" checked={selectedGroups.includes(g.paygroupCode)} readOnly className="h-4 w-4"/></div></button>)}</div>:<div className="min-h-[320px] flex items-center justify-center text-center text-gray-500 bg-gray-50 rounded-lg border border-gray-200"><div><FontAwesomeIcon icon={faUsers} className="text-xl mb-2 text-gray-400"/><h3 className="font-medium text-sm mb-1">Paygroup Selection Hidden</h3><p className="text-xs px-4">Select user(s), then click View Paygroups.</p><button onClick={view} className="mt-3 px-3 py-1.5 rounded-lg border border-blue-200 bg-blue-50 text-blue-700 text-xs font-medium">View Paygroups</button></div></div>}
  </div></div>
 </div>{selectedUsers.length>0&&<div className="mt-3 bg-blue-50 p-2 rounded text-xs">{viewing?`Assigning paygroup access to ${selectedUsers.length} selected user(s).`:`${selectedUsers.length} user(s) selected. Click "View Paygroups" to continue.`}</div>}</div>
});
export default PaygroupAccessTab;
